        curl -fsSL git.io/file-transfer | sh
144
        ./transfer cow --block 2621440 -s -p 64 --no-progress ${FIRMWARE} 2>&1 | tee cowtransfer.log
145
        echo "::warning file=cowtransfer.com::$(cat cowtransfer.log | grep https)"
146
        echo "::set-output name=url::$(cat cowtransfer.log | grep https | cut -f3 -d" ")"
147
​
148
    - name: Upload firmware to WeTransfer
149
      id: wetransfer
150
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_WETRANSFER == 'true' && !cancelled()
151
      run: |
152
        curl -fsSL git.io/file-transfer | sh
153
        ./transfer wet -s -p 16 --no-progress ${FIRMWARE} 2>&1 | tee wetransfer.log
154
        echo "::warning file=wetransfer.com::$(cat wetransfer.log | grep https)"
155
        echo "::set-output name=url::$(cat wetransfer.log | grep https | cut -f3 -d" ")"
156
​
157
    - name: Generate release tag
158
      id: tag
159
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
160
      run: |
161
        echo "::set-output name=release_tag::$(date +"%Y.%m.%d-%H%M")"
162
        touch release.txt
163
        [ $UPLOAD_COWTRANSFER = true ] && echo "🔗 [Cowtransfer](${{ steps.cowtransfer.outputs.url }})" >> release.txt
164
        [ $UPLOAD_WETRANSFER = true ] && echo "🔗 [WeTransfer](${{ steps.wetransfer.outputs.url }})" >> release.txt
165
        echo "::set-output name=status::success"
166
​
167
    - name: Upload firmware to release
168
      uses: softprops/action-gh-release@v1
169
      if: steps.tag.outputs.status == 'success' && !cancelled()
170
      env:
171
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
172
      with:
173
        tag_name: ${{ steps.tag.outputs.release_tag }}
174
        body_path: release.txt
175
        files: ${{ env.FIRMWARE }}/*
176
​
177
    - name: Delete workflow runs
178
      uses: GitRML/delete-workflow-runs@main
179
      with:
180
        retain_days: 1
181
        keep_minimum_runs: 3
182
​
183
    - name: Remove old Releases
184
      uses: dev-drprasad/delete-older-releases@v0.1.0
185
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
186
      with:
187
        keep_latest: 3
188
        delete_tags: true
189
      env:
190
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
